const GEO="https://geocoding-api.open-meteo.com/v1/search",API="https://api.open-meteo.com/v1/forecast";
const $=id=>document.getElementById(id);let data=null,unit="C";
const codes={0:["Clear sky","☀️"],1:["Mainly clear","🌤️"],2:["Partly cloudy","⛅"],3:["Overcast","☁️"],45:["Fog","🌫️"],48:["Fog","🌫️"],51:["Drizzle","🌦️"],53:["Drizzle","🌦️"],55:["Drizzle","🌧️"],61:["Rain","🌦️"],63:["Rain","🌧️"],65:["Heavy rain","🌧️"],71:["Snow","🌨️"],73:["Snow","🌨️"],75:["Heavy snow","❄️"],80:["Rain showers","🌦️"],81:["Rain showers","🌧️"],82:["Heavy showers","⛈️"],85:["Snow showers","🌨️"],86:["Heavy snow showers","❄️"],95:["Thunderstorm","⛈️"],96:["Thunderstorm","⛈️"],99:["Thunderstorm","⛈️"]};
function status(t,e=false){$("status").textContent=t;$("status").className=e?"status error":"status"}
async function geocode(city){let r=await fetch(`${GEO}?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);if(!r.ok)throw Error("Location service unavailable.");let d=await r.json();if(!d.results?.length)throw Error("City not found.");return d.results[0]}
async function weather(lat,lon,tz="auto"){let p=new URLSearchParams({latitude:lat,longitude:lon,current:"temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,uv_index",daily:"weather_code,temperature_2m_max,temperature_2m_min",timezone:tz,forecast_days:5});let r=await fetch(`${API}?${p}`);if(!r.ok)throw Error("Weather service unavailable.");return r.json()}
async function search(city){if(!city.trim())return;status("Loading weather...");try{let place=await geocode(city),w=await weather(place.latitude,place.longitude,place.timezone);data={...w,name:place.name,country:place.country,admin:place.admin1};addRecent(place.name);render();status("")}catch(e){status(e.message,true)}}
function render(){let c=data.current,info=codes[c.weather_code]||["Unknown","🌡️"],s=unit==="C"?"C":"F";$("location").textContent=[data.name,data.admin,data.country].filter(Boolean).join(", ");$("localTime").textContent=`Local time: ${new Date(c.time.replace(" ","T")).toLocaleString(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})} ${data.timezone_abbreviation||""}`;$("temp").textContent=`${Math.round(convert(c.temperature_2m))}°${s}`;$("feels").textContent=`${Math.round(convert(c.apparent_temperature))}°${s}`;$("humidity").textContent=`${c.relative_humidity_2m}%`;$("wind").textContent=`${Math.round(c.wind_speed_10m)} km/h`;$("uv").textContent=c.uv_index??"--";$("condition").textContent=info[0];$("icon").textContent=info[1];
$("forecast").innerHTML=data.daily.time.map((d,i)=>{let x=codes[data.daily.weather_code[i]]||["Unknown","🌡️"];return `<article><b>${new Date(d+"T12:00:00").toLocaleDateString(undefined,{weekday:"short"})}</b><div class="ficon">${x[1]}</div><b>${Math.round(convert(data.daily.temperature_2m_max[i]))}°${s}</b><small>${Math.round(convert(data.daily.temperature_2m_min[i]))}° / ${Math.round(convert(data.daily.temperature_2m_max[i]))}°</small></article>`}).join("");$("weatherPanel").hidden=false}
function convert(c){return unit==="C"?c:c*9/5+32}
function recent(){try{return JSON.parse(localStorage.getItem("weather-recent"))||[]}catch{return[]}}
function addRecent(city){let a=recent().filter(x=>x.toLowerCase()!=city.toLowerCase());a.unshift(city);localStorage.setItem("weather-recent",JSON.stringify(a.slice(0,6)));renderRecent()}
function renderRecent(){$("recent").innerHTML=recent().map(x=>`<button data-city="${x.replaceAll('"',"&quot;")}">${x}</button>`).join("")||'<span class="sub">No recent searches.</span>';$("recent").querySelectorAll("button").forEach(b=>b.onclick=()=>search(b.dataset.city))}
$("searchForm").onsubmit=e=>{e.preventDefault();search($("cityInput").value)};
$("unitBtn").onclick=()=>{unit=unit==="C"?"F":"C";if(data)render()};
$("clearBtn").onclick=()=>{localStorage.removeItem("weather-recent");renderRecent()};
$("locationBtn").onclick=()=>{if(!navigator.geolocation)return status("Geolocation is not supported.",true);status("Getting your location...");navigator.geolocation.getCurrentPosition(async p=>{try{let w=await weather(p.coords.latitude,p.coords.longitude);data={...w,name:"Current Location",country:"",admin:""};render();status("")}catch(e){status(e.message,true)}},()=>status("Location permission was denied or unavailable.",true))};
$("themeBtn").onclick=()=>{let dark=document.body.classList.toggle("dark");localStorage.setItem("weather-theme",dark?"dark":"light");$("themeBtn").textContent=dark?"☀️":"🌙"};
if(localStorage.getItem("weather-theme")==="dark"){$("themeBtn").click();$("themeBtn").click()}
renderRecent();search("Lagos");